### ISSUE TITLE
App doesn't start after reboots

### ISSUE THREAD

**Issue by afollestad** [pinpong/equalizer-issue-tracker#17]
It'd be nice if the app listened for the system started intent broadcast so it would automatically run after a phone reboot. 

-

Device info:
---
<table>
<tr><td>App version</td><td>1.2.8</td></tr>
<tr><td>App version code</td><td>12800</td></tr>
<tr><td>Android build version</td><td>2751853</td></tr>
<tr><td>Android release version</td><td>N</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>NPC91K</td></tr>
<tr><td>Device brand</td><td>google</td></tr>
<tr><td>Device manufacturer</td><td>Huawei</td></tr>
<tr><td>Device name</td><td>angler</td></tr>
<tr><td>Device model</td><td>Nexus 6P</td></tr>
<tr><td>Device product name</td><td>angler</td></tr>
<tr><td>Device hardware name</td><td>angler</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by pinpong** [comment]
Added in v1.3
