### ISSUE TITLE
Enhancements Dissable On Track Change

### ISSUE THREAD

**Issue by davidholt4** [pinpong/equalizer-issue-tracker#208]
The enhancements disable whenever I change my song. Then I have to tap the switches multiple times to get the effect back. 

-

Device info:
---
<table>
<tr><td>App version</td><td>1.3.7</td></tr>
<tr><td>App version code</td><td>13700</td></tr>
<tr><td>Android build version</td><td>163190903063f</td></tr>
<tr><td>Android release version</td><td>7.0</td></tr>
<tr><td>Android SDK version</td><td>24</td></tr>
<tr><td>Android build ID</td><td>NRD90U</td></tr>
<tr><td>Device brand</td><td>lge</td></tr>
<tr><td>Device manufacturer</td><td>LGE</td></tr>
<tr><td>Device name</td><td>h1</td></tr>
<tr><td>Device model</td><td>VS987</td></tr>
<tr><td>Device product name</td><td>h1_vzw</td></tr>
<tr><td>Device hardware name</td><td>h1</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by heinrichreimer** [comment]
Issue description doesn't include specific crash details.
