### ISSUE TITLE
App gets reset

### ISSUE THREAD

**Issue by piyushpaliwal** [pinpong/equalizer-issue-tracker#22]
I have chosen the option to start on boot but this didn't work. All my settings were reset upon restart and even after setting the desired levels if I open the app, bass boost and surround are getting reset.

-

Device info:
---
<table>
<tr><td>App version</td><td>1.3</td></tr>
<tr><td>App version code</td><td>13000</td></tr>
<tr><td>Android build version</td><td>2751853</td></tr>
<tr><td>Android release version</td><td>N</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>NPC91K</td></tr>
<tr><td>Device brand</td><td>google</td></tr>
<tr><td>Device manufacturer</td><td>Huawei</td></tr>
<tr><td>Device name</td><td>angler</td></tr>
<tr><td>Device model</td><td>Nexus 6P</td></tr>
<tr><td>Device product name</td><td>angler</td></tr>
<tr><td>Device hardware name</td><td>angler</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by HeinrichReimer** [comment]
We fixed that internally. We'll roll out an update soon.
