### ISSUE TITLE
When dismissing application equalizer stops

### ISSUE THREAD

**Issue by nathaneltitane** [pinpong/equalizer-issue-tracker#26]
Dismissing equalizer from recents kills process and disables applocation

-

Device info:
---
<table>
<tr><td>App version</td><td>1.3</td></tr>
<tr><td>App version code</td><td>13000</td></tr>
<tr><td>Android build version</td><td>2705526</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MHC19Q</td></tr>
<tr><td>Device brand</td><td>google</td></tr>
<tr><td>Device manufacturer</td><td>Huawei</td></tr>
<tr><td>Device name</td><td>angler</td></tr>
<tr><td>Device model</td><td>Nexus 6P</td></tr>
<tr><td>Device product name</td><td>angler</td></tr>
<tr><td>Device hardware name</td><td>angler</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by HeinrichReimer** [comment]
If you have the notification turned off the phone will kill the equalizer when it needs memory for other apps. Turning the notification on will ensure that the system won't kill the equalizer.
