### ISSUE TITLE
New style for selecting theme

### ISSUE THREAD

**Issue by AkshayChordiya** [pinpong/equalizer-issue-tracker#27]
Well this is optional and I'm just trying the reporting mechanism. 

-

Device info:
---
<table>
<tr><td>App version</td><td>1.3</td></tr>
<tr><td>App version code</td><td>13000</td></tr>
<tr><td>Android build version</td><td>2704746</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MOB30D</td></tr>
<tr><td>Device brand</td><td>google</td></tr>
<tr><td>Device manufacturer</td><td>LGE</td></tr>
<tr><td>Device name</td><td>hammerhead</td></tr>
<tr><td>Device model</td><td>Nexus 5</td></tr>
<tr><td>Device product name</td><td>hammerhead</td></tr>
<tr><td>Device hardware name</td><td>hammerhead</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

**Comment by HeinrichReimer** [comment]
What style do you want?

**Comment by AkshayChordiya** [comment]
New activity where we get a grid of all the themes and can preview each one and buy from there only.
