### ISSUE TITLE
after to many opens no sound when device is locked for little time

### ISSUE THREAD

**Issue by GeForcez** [pinpong/equalizer-issue-tracker#300]
after some time and serveral times i opened this app it stops the sound if the device is locked for a minute or two. if you light up the screen not even needed to unlock it starts playing again. also trying to restart the apps does not work only thing that fixes the issue is a full restart of the phone. (this issue only presists after it worked a long time and i reopened the app after a while).

-

Device info:
---
<table>
<tr><td>App version</td><td>1.3.7</td></tr>
<tr><td>App version code</td><td>13700</td></tr>
<tr><td>Android build version</td><td>C432B102</td></tr>
<tr><td>Android release version</td><td>7.0</td></tr>
<tr><td>Android SDK version</td><td>24</td></tr>
<tr><td>Android build ID</td><td>WAS-LX1AC432B102</td></tr>
<tr><td>Device brand</td><td>HUAWEI</td></tr>
<tr><td>Device manufacturer</td><td>HUAWEI</td></tr>
<tr><td>Device name</td><td>HWWAS-H</td></tr>
<tr><td>Device model</td><td>WAS-LX1A</td></tr>
<tr><td>Device product name</td><td>WAS-LX1A</td></tr>
<tr><td>Device hardware name</td><td>hi6250</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by heinrichreimer** [comment]
We're working on this issue for the next release.
Until then it would be great if you could send a video of this issue happening.
