### ISSUE TITLE
Settings never stay the same

### ISSUE THREAD

**Issue by piyushpaliwal** [pinpong/equalizer-issue-tracker#37]
Using this since long now and its quite unfortunate and frustrating to change and save the settings on a daily basis or rather I should say thrice a day. You mentioned previously that its a known thing and has been resolved but doesn't seems to be the case. Can't you convert this into a service or something so it just stays in the background without actually coming in UI anywhere just like MusicFX? 
## 
## Device info:

<table>
<tr><td>App version</td><td>1.3.2</td></tr>
<tr><td>App version code</td><td>13200</td></tr>
<tr><td>Android build version</td><td>2705526</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MHC19Q</td></tr>
<tr><td>Device brand</td><td>google</td></tr>
<tr><td>Device manufacturer</td><td>Huawei</td></tr>
<tr><td>Device name</td><td>angler</td></tr>
<tr><td>Device model</td><td>Nexus 6P</td></tr>
<tr><td>Device product name</td><td>angler</td></tr>
<tr><td>Device hardware name</td><td>angler</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by HeinrichReimer** [comment]
The service does run in background and all settings are stored persistently in either our database or local storage. Please update the app and if your phone's rooted check that there are no concurrent services running that kill Equalizer's service.
