### ISSUE TITLE
Intensificador de volume não funciona.

### ISSUE THREAD

**Issue by gleissongtr** [pinpong/equalizer-issue-tracker#93]
Intensificador de volume não funciona no meu lg g3

-

Device info:
---
<table>
<tr><td>App version</td><td>1.3.3</td></tr>
<tr><td>App version code</td><td>13300</td></tr>
<tr><td>Android build version</td><td>1441135455</td></tr>
<tr><td>Android release version</td><td>5.0</td></tr>
<tr><td>Android SDK version</td><td>21</td></tr>
<tr><td>Android build ID</td><td>LRX21R</td></tr>
<tr><td>Device brand</td><td>lge</td></tr>
<tr><td>Device manufacturer</td><td>LGE</td></tr>
<tr><td>Device name</td><td>g3</td></tr>
<tr><td>Device model</td><td>LG-D855</td></tr>
<tr><td>Device product name</td><td>g3_global_com</td></tr>
<tr><td>Device hardware name</td><td>g3</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

**Comment by HeinrichReimer** [comment]
Please read the read the README. Only English and German issues are allowed.
