### ISSUE TITLE
Pocket Casts

### ISSUE THREAD

**Issue by Inukinator** [pinpong/equalizer-issue-tracker#94]
Doesn't work with pocket casts, I've contacted their support too for good measure! 

-

Device info:
---
<table>
<tr><td>App version</td><td>1.3.3</td></tr>
<tr><td>App version code</td><td>13300</td></tr>
<tr><td>Android build version</td><td>3085278</td></tr>
<tr><td>Android release version</td><td>7.0</td></tr>
<tr><td>Android SDK version</td><td>24</td></tr>
<tr><td>Android build ID</td><td>NRD90M</td></tr>
<tr><td>Device brand</td><td>google</td></tr>
<tr><td>Device manufacturer</td><td>Huawei</td></tr>
<tr><td>Device name</td><td>angler</td></tr>
<tr><td>Device model</td><td>Nexus 6P</td></tr>
<tr><td>Device product name</td><td>angler</td></tr>
<tr><td>Device hardware name</td><td>angler</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by HeinrichReimer** [comment]
Pocket Casts doesn't send the specific intent needed to activate audio effects. If they add that we can support their app too.

**Comment by pinpong** [comment]
@Inukinator i'll contact the dev team from Pocket Casts.
